### ISSUE TITLE
contract evaluateTransaction doesn't throw an error if the chaincode responds with an error

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#193]
Using node.js chaincode and node.js thin client I execute a submit transaction where the transaction name doesn't exist and the contract api returns an error informing you of the fact. the submit throws an error and the error provides appropriate detail
```
Error: 10 ABORTED: failed to endorse transaction: [{address:"peer0.org1.example.com:7051" msp_id:"Org1MSP" message:"error 500, error in simulation: transaction returned with failure: Error: You've asked to invoke a function that does not exist: put" }]
```

Doing the same using evaluate transaction on a contract results in an empty response, no error is thrown and the contract definitely reports that the function name doesn't exist

```
2021-09-14 16:04:06.481 UTC 00ec ERRO [endorser] simulateProposal -> failed to invoke chaincode basic, error: transaction returned with failure: Error: You've asked to invoke a function that does not exist: ReadAsset1
github.com/hyperledger/fabric/core/chaincode.processChaincodeExecutionResult
        /go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:188
github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Execute
        /go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:162
github.com/hyperledger/fabric/core/endorser.(*SupportImpl).Execute
        /go/src/github.com/hyperledger/fabric/core/endorser/support.go:126
github.com/hyperledger/fabric/core/endorser.(*Endorser).callChaincode
        /go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:119
github.com/hyperledger/fabric/core/endorser.(*Endorser).simulateProposal
        /go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:186
github.com/hyperledger/fabric/core/endorser.(*Endorser).ProcessProposalSuccessfullyOrError
        /go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:402
github.com/hyperledger/fabric/core/endorser.(*Endorser).ProcessProposal
        /go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:344
github.com/hyperledger/fabric/internal/pkg/gateway.(*EndorserServerAdapter).ProcessProposal
        /go/src/github.com/hyperledger/fabric/internal/pkg/gateway/gateway.go:38
github.com/hyperledger/fabric/internal/pkg/gateway.(*Server).Evaluate
        /go/src/github.com/hyperledger/fabric/internal/pkg/gateway/api.go:66
github.com/hyperledger/fabric-protos-go/gateway._Gateway_Evaluate_Handler.func1
        /go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/gateway/gateway.pb.go:1185
github.com/hyperledger/fabric/internal/peer/node.unaryGrpcLimiter.func1
        /go/src/github.com/hyperledger/fabric/internal/peer/node/grpc_limiters.go:44
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/hyperledger/fabric/common/grpclogging.UnaryServerInterceptor.func1
        /go/src/github.com/hyperledger/fabric/common/grpclogging/server.go:92
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/hyperledger/fabric/common/grpcmetrics.UnaryServerInterceptor.func1
        /go/src/github.com/hyperledger/fabric/common/grpcmetrics/interceptor.go:31
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
        /go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34
github.com/hyperledger/fabric-protos-go/gateway._Gateway_Evaluate_Handler
        /go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/gateway/gateway.pb.go:1187
google.golang.org/grpc.(*Server).processUnaryRPC
        /go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1180
google.golang.org/grpc.(*Server).handleStream
        /go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1503
google.golang.org/grpc.(*Server).serveStreams.func1.2
        /go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:843
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1371 channel=mychannel txID=611d2cc7
2021-09-14 16:04:06.481 UTC 00ed WARN [endorser] ProcessProposal -> Failed to invoke chaincode channel=mychannel chaincode=basic error="error in simulation: transaction returned with failure: Error: You've asked to invoke a function that does not exist: ReadAsset1"
2021-09-14 16:04:06.481 UTC 00ee INFO [comm.grpc.server] 1 -> unary call completed grpc.service=gateway.Gateway grpc.method=Evaluate grpc.peer_address=172.21.0.1:34772 grpc.code=OK grpc.call_duration=5.8841ms
```

**Comment by davidkel** [comment]
Just to confirm, the same thing happens with the Go Client and is actually worse as the application crashes
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8b31a1]

goroutine 1 [running]:
github.com/hyperledger/fabric-gateway/pkg/client.(*Proposal).Evaluate(0xc000572c00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/dave/github-mine/fabric-gateway/pkg/client/proposal.go:100 +0x201
github.com/hyperledger/fabric-gateway/pkg/client.(*Contract).Evaluate(0xc00052be28, 0x9d8610, 0x3, 0xc00052bd40, 0x1, 0x1, 0x0, 0x0, 0x2c, 0xc00063a270, ...)
        /home/dave/github-mine/fabric-gateway/pkg/client/contract.go:71 +0xb6
github.com/hyperledger/fabric-gateway/pkg/client.(*Contract).EvaluateTransaction(0xc00052be28, 0x9d8610, 0x3, 0xc00052bdf0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/dave/github-mine/fabric-gateway/pkg/client/contract.go:59 +0xa5
main.exampleSubmit(0xc00000ec18)
        /home/dave/github-mine/fabric-gateway/samples/go/sample.go:87 +0x290
main.main()
        /home/dave/github-mine/fabric-gateway/samples/go/sample.go:47 +0x1b9
```

**Comment by bestbeforetoday** [comment]
The Go client behaviour might be slightly better now as I've made some changes to reduce the likelihood of panics on incomplete or malformed protobuf messages, but it won't be any more correct. It seems the evaluate service in the peer isn't responding correctly to errors from Node chaincode.

**Comment by bestbeforetoday** [comment]
Relates to #178

**Comment by davidkel** [comment]
@bestbeforetoday This scenario I've just tested could also be related, I have node chaincode that crashes the chaincode instance when a transaction is called. If I Submit from a Go client then I get 
```
rpc error: code = Aborted desc = failed to endorse transaction: [{address:"org1peer-api.127-0-0-1.nip.io:8080" msp_id:"Org1MSP" message:"error 500, error in simulation: failed to execute transaction b3fc9cd874f85f7aa01acf95066b66737de520a941240164cd3f3e7324f2d898: error sending: chaincode stream terminated" }]
```

However calling the same crash transaction from an evaluate in the Go client (doesn't crash the go client anymore) but I don't get an error, all I get is an empty response.  The error `chaincode stream terminated` I would assume comes from the peer so not related to node chaincode in this case but still no error is returned to the client. I see the same behaviour from the node client as well

**Comment by davidkel** [comment]
@bestbeforetoday 
Further test results here from java client and assume the same for node and go
1. When using go chaincode I get the proposal error on evaluate and submit
2. When using node chaincode I only get the proposal error on submit  (even though it is the same transaction being invoked)

When testing the crashing of chaincode, the issue is consistent no matter what the chaincode type was (which was expected really)
