### ISSUE TITLE
Intermittent private data scenario test failure

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-gateway#388]
```
  Scenario: Org1 writes private data to SharedCollection without specifying endorsers                                                                                                      # /home/vsts/work/1/s/scenario/features/privatedata.feature:105
    When I use the gateway named gateway1                                                                                                                                                  # scenario_test.go:165 -> github.com/hyperledger/fabric-gateway/scenario/go.useGateway
    And I prepare to submit a WritePrivateData transaction                                                                                                                                 # scenario_test.go:188 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set transient data on the transaction to                                                                                                                                         # scenario_test.go:230 -> github.com/hyperledger/fabric-gateway/scenario/go.setTransientData
      | collection | SharedCollection |
      | key        | key-108          |
      | value      | value-108        |
    And I invoke the transaction                                                                                                                                                           # scenario_test.go:250 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    And I prepare to evaluate a ReadPrivateData transaction                                                                                                                                # scenario_test.go:188 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set the transaction arguments to ["SharedCollection", "key-108"]                                                                                                                 # scenario_test.go:199 -> github.com/hyperledger/fabric-gateway/scenario/go.setArguments
    And I set the endorsing organizations to ["Org1MSP"]                                                                                                                                   # scenario_test.go:240 -> github.com/hyperledger/fabric-gateway/scenario/go.setEndorsingOrgs
    And I invoke the transaction                                                                                                                                                           # scenario_test.go:250 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    Then the response should be "value-108"                                                                                                                                                # scenario_test.go:308 -> github.com/hyperledger/fabric-gateway/scenario/go.theResponseShouldBe
    transaction response "" does not match expected value "value-108"
```

**Comment by bestbeforetoday** [comment]
Another one in the same test feature:
```
Scenario: Org1 writes private data to SharedCollection and Org3Collection without specifying endorsers                                                                                   # ///home/vsts/work/1/s/java/../scenario/features/privatedata.feature:120
  Given I have deployed a Fabric network                                                                                                                                                 # scenario.ScenarioSteps.deployFabricNetwork()
  And I have created and joined all channels                                                                                                                                             # scenario.ScenarioSteps.createAndJoinAllChannels()
  And I deploy golang chaincode named private at version 1.0.0 for all organizations on channel mychannel with endorsement policy OR("Org1MSP.member","Org2MSP.member","Org3MSP.member") # scenario.ScenarioSteps.deployChaincode(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
  And I create a gateway named gateway1 for user User1 in MSP Org1MSP                                                                                                                    # scenario.ScenarioSteps.createGateway(java.lang.String,java.lang.String,java.lang.String)
  And I connect the gateway to peer0.org1.example.com                                                                                                                                    # scenario.ScenarioSteps.connectGateway(java.lang.String)
  And I use the mychannel network                                                                                                                                                        # scenario.ScenarioSteps.useNetwork(java.lang.String)
  And I use the private contract                                                                                                                                                         # scenario.ScenarioSteps.useContract(java.lang.String)
  And I create a gateway named gateway2 for user User1 in MSP Org2MSP                                                                                                                    # scenario.ScenarioSteps.createGateway(java.lang.String,java.lang.String,java.lang.String)
  And I connect the gateway to peer0.org2.example.com                                                                                                                                    # scenario.ScenarioSteps.connectGateway(java.lang.String)
  And I use the mychannel network                                                                                                                                                        # scenario.ScenarioSteps.useNetwork(java.lang.String)
  And I use the private contract                                                                                                                                                         # scenario.ScenarioSteps.useContract(java.lang.String)
  And I use the gateway named gateway1                                                                                                                                                   # scenario.ScenarioSteps.useGateway(java.lang.String)
  When I use the gateway named gateway1                                                                                                                                                  # scenario.ScenarioSteps.useGateway(java.lang.String)
  And I prepare to submit a WritePrivateData transaction                                                                                                                                 # scenario.ScenarioSteps.prepareTransaction(java.lang.String,java.lang.String)
  And I set transient data on the transaction to                                                                                                                                         # scenario.ScenarioSteps.setTransientData(io.cucumber.datatable.DataTable)
    | collection | SharedCollection,Org3Collection |
    | key        | key-109                         |
    | value      | value-109                       |
  And I invoke the transaction                                                                                                                                                           # scenario.ScenarioSteps.invokeSuccessfulTransaction()
  And I prepare to evaluate a ReadPrivateData transaction                                                                                                                                # scenario.ScenarioSteps.prepareTransaction(java.lang.String,java.lang.String)
  And I set the transaction arguments to ["SharedCollection", "key-109"]                                                                                                                 # scenario.ScenarioSteps.setTransactionArguments(java.lang.String)
  And I set the endorsing organizations to ["Org1MSP"]                                                                                                                                   # scenario.ScenarioSteps.setEndorsingOrgs(java.lang.String)
  And I invoke the transaction                                                                                                                                                           # scenario.ScenarioSteps.invokeSuccessfulTransaction()
  Then the response should be "value-109"                                                                                                                                                # scenario.ScenarioSteps.assertResponse(java.lang.String)
      org.opentest4j.AssertionFailedError: 
expected: "value-109"
 but was: ""
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at scenario.ScenarioSteps.assertResponse(ScenarioSteps.java:430)
	at ✽.the response should be "value-109"(file:///home/vsts/work/1/s/java/../scenario/features/privatedata.feature:132)
```

**Comment by bestbeforetoday** [comment]
And another one, failing quite frequently in Go scenario tests:
```
  Scenario: Org2 writes private data to Org1Collection (Org1MSP must endorse), and Org1 can read it                                                                                        # /home/runner/work/fabric-gateway/fabric-gateway/scenario/features/privatedata.feature:62
    When I use the gateway named gateway2                                                                                                                                                  # scenario_test.go:195 -> github.com/hyperledger/fabric-gateway/scenario/go.useGateway
    And I prepare to submit a WritePrivateData transaction                                                                                                                                 # scenario_test.go:218 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set transient data on the transaction to                                                                                                                                         # scenario_test.go:260 -> github.com/hyperledger/fabric-gateway/scenario/go.setTransientData
      | collection | Org1Collection |
      | key        | key-104        |
      | value      | value-104      |
    And I set the endorsing organizations to ["Org1MSP"]                                                                                                                                   # scenario_test.go:270 -> github.com/hyperledger/fabric-gateway/scenario/go.setEndorsingOrgs
    And I invoke the transaction                                                                                                                                                           # scenario_test.go:280 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    And I use the gateway named gateway1                                                                                                                                                   # scenario_test.go:195 -> github.com/hyperledger/fabric-gateway/scenario/go.useGateway
    And I prepare to evaluate a ReadPrivateData transaction                                                                                                                                # scenario_test.go:218 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set the transaction arguments to ["Org1Collection", "key-104"]                                                                                                                   # scenario_test.go:229 -> github.com/hyperledger/fabric-gateway/scenario/go.setArguments
    And I set the endorsing organizations to ["Org1MSP"]                                                                                                                                   # scenario_test.go:270 -> github.com/hyperledger/fabric-gateway/scenario/go.setEndorsingOrgs
    And I invoke the transaction                                                                                                                                                           # scenario_test.go:280 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    Then the response should be "value-104"                                                                                                                                                # scenario_test.go:338 -> github.com/hyperledger/fabric-gateway/scenario/go.theResponseShouldBe
    transaction response "" does not match expected value "value-104"
```

**Comment by bestbeforetoday** [comment]
A Java failure:
```
Scenario: Org1 writes private data to Org1Collection but fails to read it via an Org2 peer                                                                                               # ///home/runner/work/fabric-gateway/fabric-gateway/java/../scenario/features/privatedata.feature:35
  Given I have deployed a Fabric network                                                                                                                                                 # scenario.ScenarioSteps.deployFabricNetwork()
  And I have created and joined all channels                                                                                                                                             # scenario.ScenarioSteps.createAndJoinAllChannels()
  And I deploy golang chaincode named private at version 1.0.0 for all organizations on channel mychannel with endorsement policy OR("Org1MSP.member","Org2MSP.member","Org3MSP.member") # scenario.ScenarioSteps.deployChaincode(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
  And I create a gateway named gateway1 for user User1 in MSP Org1MSP                                                                                                                    # scenario.ScenarioSteps.createGateway(java.lang.String,java.lang.String,java.lang.String)
  And I connect the gateway to peer0.org1.example.com                                                                                                                                    # scenario.ScenarioSteps.connectGateway(java.lang.String)
  And I use the mychannel network                                                                                                                                                        # scenario.ScenarioSteps.useNetwork(java.lang.String)
  And I use the private contract                                                                                                                                                         # scenario.ScenarioSteps.useContract(java.lang.String)
  And I create a gateway named gateway2 for user User1 in MSP Org2MSP                                                                                                                    # scenario.ScenarioSteps.createGateway(java.lang.String,java.lang.String,java.lang.String)
  And I connect the gateway to peer0.org2.example.com                                                                                                                                    # scenario.ScenarioSteps.connectGateway(java.lang.String)
  And I use the mychannel network                                                                                                                                                        # scenario.ScenarioSteps.useNetwork(java.lang.String)
  And I use the private contract                                                                                                                                                         # scenario.ScenarioSteps.useContract(java.lang.String)
  And I use the gateway named gateway1                                                                                                                                                   # scenario.ScenarioSteps.useGateway(java.lang.String)
  When I prepare to submit a WritePrivateData transaction                                                                                                                                # scenario.ScenarioSteps.prepareTransaction(java.lang.String,java.lang.String)
  And I set transient data on the transaction to                                                                                                                                         # scenario.ScenarioSteps.setTransientData(io.cucumber.datatable.DataTable)
    | collection | Org1Collection |
    | key        | key-102        |
    | value      | value-102      |
  And I set the endorsing organizations to ["Org1MSP"]                                                                                                                                   # scenario.ScenarioSteps.setEndorsingOrgs(java.lang.String)
  And I invoke the transaction                                                                                                                                                           # scenario.ScenarioSteps.invokeSuccessfulTransaction()
  And I prepare to evaluate a ReadPrivateData transaction                                                                                                                                # scenario.ScenarioSteps.prepareTransaction(java.lang.String,java.lang.String)
  And I set the transaction arguments to ["Org1Collection", "key-102"]                                                                                                                   # scenario.ScenarioSteps.setTransactionArguments(java.lang.String)
  And I set the endorsing organizations to ["Org2MSP"]                                                                                                                                   # scenario.ScenarioSteps.setEndorsingOrgs(java.lang.String)
  Then the transaction invocation should fail                                                                                                                                            # scenario.ScenarioSteps.assertTransactionFails()
      java.lang.AssertionError: No transaction error. Response was: 
	at scenario.TransactionInvocation.getError(TransactionInvocation.java:153)
	at scenario.ScenarioSteps.assertTransactionFails(ScenarioSteps.java:533)
	at ✽.the transaction invocation should fail(file:///home/runner/work/fabric-gateway/fabric-gateway/java/../scenario/features/privatedata.feature:46)
```

**Comment by bestbeforetoday** [comment]
These failures have not been observed in the last couple of months so closing.
