### ISSUE TITLE
Intermittent SBE scenario test failure

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-gateway#545]
```
Scenario: Set SBE policy for Org2 AND Org3 (no local org); state change successfully when not specifying endorsing orgs
        # /home/runner/work/fabric-gateway/fabric-gateway/scenario/features/sbe.feature:51
    When I prepare to submit a SetStateEndorsers transaction
        # scenario_test.go:218 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set the transaction arguments to ["key-001", "Org2MSP", "Org3MSP"]
        # scenario_test.go:229 -> github.com/hyperledger/fabric-gateway/scenario/go.setArguments
    And I invoke the transaction
        # scenario_test.go:280 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    And I prepare to submit a ChangeState transaction
        # scenario_test.go:218 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set the transaction arguments to ["key-001", "value-Org2-Org3"]
        # scenario_test.go:229 -> github.com/hyperledger/fabric-gateway/scenario/go.setArguments
    And I invoke the transaction
        # scenario_test.go:280 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    And I prepare to evaluate a GetState transaction
        # scenario_test.go:218 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set the transaction arguments to ["key-001"]
        # scenario_test.go:229 -> github.com/hyperledger/fabric-gateway/scenario/go.setArguments
    And I invoke the transaction
        # scenario_test.go:280 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    Then the response should be "value-Org2-Org3"
        # scenario_test.go:338 -> github.com/hyperledger/fabric-gateway/scenario/go.theResponseShouldBe
    transaction response "value-001" does not match expected value "value-Org2-Org3"
```

**Comment by bestbeforetoday** [comment]
Another one:

```
Scenario: State change must be endorsed by Org1 peer
# ///home/runner/work/fabric-gateway/fabric-gateway/java/../scenario/features/sbe.feature:19
  Given I have deployed a Fabric network
# scenario.ScenarioSteps.deployFabricNetwork()
  And I have created and joined all channels
# scenario.ScenarioSteps.createAndJoinAllChannels()
  And I deploy golang chaincode named private at version 1.0.0 for all organizations on channel mychannel with endorsement policy OR("Org1MSP.member","Org2MSP.member","Org3MSP.member") # scenario.ScenarioSteps.deployChaincode(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
  And I create a gateway named gateway1 for user User1 in MSP Org1MSP
# scenario.ScenarioSteps.createGateway(java.lang.String,java.lang.String,java.lang.String)
  And I connect the gateway to peer0.org1.example.com
# scenario.ScenarioSteps.connectGateway(java.lang.String)
  And I use the mychannel network
# scenario.ScenarioSteps.useNetwork(java.lang.String)
  And I use the private contract                                                                                                                                                         # scenario.ScenarioSteps.useContract(java.lang.String)
  And I prepare to submit a SetStateWithEndorser transaction
# scenario.ScenarioSteps.prepareTransaction(java.lang.String,java.lang.String)
  And I set the transaction arguments to ["key-001", "value-001", "Org1MSP"]
# scenario.ScenarioSteps.setTransactionArguments(java.lang.String)
  And I invoke the transaction                                                                                                                                                           # scenario.ScenarioSteps.invokeSuccessfulTransaction()
  When I prepare to submit a ChangeState transaction
# scenario.ScenarioSteps.prepareTransaction(java.lang.String,java.lang.String)
  And I set the transaction arguments to ["key-001", "value-Org1"]
# scenario.ScenarioSteps.setTransactionArguments(java.lang.String)
  And I set the endorsing organizations to ["Org1MSP"]
# scenario.ScenarioSteps.setEndorsingOrgs(java.lang.String)
  And I invoke the transaction                                                                                                                                                           # scenario.ScenarioSteps.invokeSuccessfulTransaction()
  And I prepare to evaluate a GetState transaction
# scenario.ScenarioSteps.prepareTransaction(java.lang.String,java.lang.String)
  And I set the transaction arguments to ["key-001"]
# scenario.ScenarioSteps.setTransactionArguments(java.lang.String)
  And I invoke the transaction                                                                                                                                                           # scenario.ScenarioSteps.invokeSuccessfulTransaction()
  Then the response should be "value-Org1"
# scenario.ScenarioSteps.assertResponse(java.lang.String)
      org.opentest4j.AssertionFailedError: 
expected: "value-Org1"
 but was: "value-001"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at scenario.ScenarioSteps.assertResponse(ScenarioSteps.java:545)
	at ✽.the response should be "value-Org1"(file:///home/runner/work/fabric-gateway/fabric-gateway/java/../scenario/features/sbe.feature:27)
```

**Comment by bestbeforetoday** [comment]
And another:

```
Scenario: Set SBE policy for Org1 AND Org3; state change successfully when not specifying endorsing orgs
# /home/runner/work/fabric-gateway/fabric-gateway/scenario/features/sbe.feature:39
    When I prepare to submit a SetStateEndorsers transaction
# scenario_test.go:218 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set the transaction arguments to ["key-001", "Org1MSP", "Org3MSP"]
# scenario_test.go:229 -> github.com/hyperledger/fabric-gateway/scenario/go.setArguments
    And I invoke the transaction
# scenario_test.go:280 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    And I prepare to submit a ChangeState transaction
# scenario_test.go:218 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set the transaction arguments to ["key-001", "value-Org1-Org3"]
# scenario_test.go:229 -> github.com/hyperledger/fabric-gateway/scenario/go.setArguments
    And I invoke the transaction
# scenario_test.go:280 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    And I prepare to evaluate a GetState transaction
# scenario_test.go:218 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set the transaction arguments to ["key-001"]
# scenario_test.go:229 -> github.com/hyperledger/fabric-gateway/scenario/go.setArguments
    And I invoke the transaction
# scenario_test.go:280 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    Then the response should be "value-Org1-Org3"
# scenario_test.go:338 -> github.com/hyperledger/fabric-gateway/scenario/go.theResponseShouldBe
    transaction response "value-001" does not match expected value "value-Org1-Org3"
```

**Comment by bestbeforetoday** [comment]
Yet another one:
```
Scenario: Set SBE policy for Org1 AND Org3; state change fails when specifying incorrect endorsing orgs
# /home/runner/work/fabric-gateway/fabric-gateway/scenario/features/sbe.feature:63
    When I prepare to submit a SetStateEndorsers transaction
# scenario_test.go:218 -> github.com/hyperledger/fabric-gateway/scenario/go.prepareTransaction
    And I set the transaction arguments to ["key-001", "Org1MSP", "Org3MSP"]
# scenario_test.go:229 -> github.com/hyperledger/fabric-gateway/scenario/go.setArguments
    And I invoke the transaction
# scenario_test.go:280 -> github.com/hyperledger/fabric-gateway/scenario/go.invokeSuccessfulTransaction
    commit failed with status ENDORSEMENT_POLICY_FAILURE (ENDORSEMENT_POLICY_FAILURE)

**Comment by bestbeforetoday** [comment]
These failures have not been observed in the last couple of months so closing.
