### ISSUE TITLE
Intermittent failure in Java eventing unit tests

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-gateway#696]
Errors similar to this periodically occur in the automated build:
```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.hyperledger.fabric.client.CommonBlockEventsTest.uses_checkpoint_block_zero_with_set_transaction_id_instead_of_specified_start_block(CommonBlockEventsTest.java:263)
```

I suspect this is caused by a concurrency issue in the capture of events by the Mockito mocks. It might be necessary to use explicit synchronization to ensure values are visible to the calling thread.

**Comment by bestbeforetoday** [comment]
Intermittent failures are still occurring, such as:

```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.hyperledger.fabric.client.CommonBlockEventsTest.sends_valid_request_with_specified_start_block_number(CommonBlockEventsTest.java:155)
```
and
```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.hyperledger.fabric.client.CommonBlockEventsTest.sends_valid_request_with_specified_start_block_number_using_sign_bit_for_unsigned_64bit_value(CommonBlockEventsTest.java:175)
```
